STATUS_ACCEPTED = "ACCEPTED"
STATUS_PENDING = "PENDING"
STATUS_DECLINED = "DECLINED"

INVITATION_STATUS_CHOICES = [
    (STATUS_ACCEPTED, 'Accepted'),
    (STATUS_PENDING, 'Pending'),
    (STATUS_DECLINED, 'Declined'),
]