# Generated by Django 5.0.7 on 2024-07-20 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='blocked_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_as_blocked', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='blocker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_as_blocker', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_friend', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_user', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
