# Generated by Django 5.0.7 on 2024-07-20 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_blocked_blocked_id_alter_blocked_blocker_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocked',
            old_name='blocked_id',
            new_name='blocked',
        ),
        migrations.RenameField(
            model_name='blocked',
            old_name='blocker_id',
            new_name='blocker',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend_id',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='blocked',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_friend'),
        ),
    ]
