# Generated by Django 5.0.7 on 2024-07-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_display_name_friendrequest_delete_friend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('declined', 'declined')], max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_invitation_as_receiver', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_invitation_as_sender', to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.AddConstraint(
            model_name='friendinvitation',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_friend_invitation'),
        ),
    ]
