# Generated by Django 5.0.7 on 2024-07-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friendinvitation_delete_friendrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitation',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], max_length=20),
        ),
    ]
