# Generated by Django 5.0.7 on 2024-07-23 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_invitations', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_invitations', to='users.profile'),
        ),
    ]
