# Generated by Django 5.0.7 on 2024-07-23 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_blocked_blocked_alter_blocked_blocker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker_blocked_users', to='users.profile'),
        ),
    ]
