# Generated by Django 5.0.7 on 2024-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('REMOTE', 'Remote'), ('LOCAL', 'Local')])),
                ('status', models.CharField(choices=[('IN_PREPARATION', 'In preparation'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PREPARATION', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserTournamentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='PENDING', max_length=50)),
            ],
        ),
    ]
