# Generated by Django 5.0.7 on 2024-07-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_created', to='users.profile'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_won', to='users.profile'),
        ),
        migrations.AddField(
            model_name='usertournamentinvitation',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_users', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='usertournamentinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tournaments', to='users.profile'),
        ),
        migrations.AddConstraint(
            model_name='usertournamentinvitation',
            constraint=models.UniqueConstraint(fields=('user', 'tournament'), name='unique_tournament_invitation'),
        ),
    ]
