# Generated by Django 5.0.7 on 2024-07-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('LOCAL', 'Local')]),
        ),
        migrations.AlterField(
            model_name='tournamentinvitation',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')]),
        ),
    ]
