# Generated by Django 5.0.7 on 2024-08-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_1v1',
            field=models.BooleanField(default=False),
        ),
    ]
