# Generated by Django 5.0.7 on 2024-07-23 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_type_and_more'),
        ('users', '0008_alter_blocked_blocked_alter_blocked_blocker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinvitation',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tournament_invitations', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='tournamentinvitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tournament_invitations', to='users.profile'),
        ),
    ]
