# Generated by Django 5.0.7 on 2024-07-25 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_usertournament_tournament_and_more'),
        ('users', '0009_alter_blocked_blocked_alter_blocked_blocker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertournament',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='usertournament',
            name='user',
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('IN_PREPARATION', 'In preparationn'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PREPARATION', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_won', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_created', to='users.profile'),
        ),
        migrations.CreateModel(
            name='UserTournamentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='PENDING', max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_users', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tournaments', to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='TournamentInvitation',
        ),
        migrations.DeleteModel(
            name='UserTournament',
        ),
        migrations.AddConstraint(
            model_name='usertournamentinvitation',
            constraint=models.UniqueConstraint(fields=('user', 'tournament'), name='unique_tournament_invitation'),
        ),
    ]
