# Generated by Django 5.0.7 on 2024-07-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_remove_usertournament_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('IN_PREPARATION', 'In preparation'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PREPARATION', max_length=50),
        ),
    ]
