# Generated by Django 5.0.7 on 2024-07-23 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_finished_at_alter_game_tournament_and_more'),
        ('tournaments', '0003_alter_tournamentinvitation_receiver_and_more'),
        ('users', '0008_alter_blocked_blocked_alter_blocked_blocker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_users', to='games.game'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to='users.profile'),
        ),
    ]
